name: Build and Publish

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
        registry-url: https://npm.pkg.github.com/
        scope: "@allbin"
    - name: npm install, build, and test
      run: |
        yarn install --frozen-lockfile
        yarn build
      env:
        CI: true
    - name: publish
      run: |
        echo "registry=https://npm.pkg.github.com/allbin" > .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
        yarn publish
