name: Build and publish NPM package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
        scope: @allbin
    - name: npm install, build, and test
      run: |
        yarn install --frozen-lockfile
        yarn build
        yarn publish --access restricted
      env:
        CI: true
